<template>
  <q-page>
    <div class="q-pa-md row justify-center">
      <div style="width: 100%">
        <q-infinite-scroll @load="loadMore" reverse>
          <div v-for="(message, index) in messages" :key="index">
            <q-chat-message :name="message.name" :sent="message.sent" :stamp="message.stamp" :text="message.text">
            </q-chat-message>
          </div>
        </q-infinite-scroll>
      </div>
    </div>
  </q-page>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

// Dummy data generated by AI
const messages = [
  {
    name: 'Jon Doe',
    sent: true,
    stamp: '12:34',
    text: ['Hello, how are you?'],
  },
  {
    name: 'Jane Smith',
    sent: false,
    stamp: '12:36',
    text: ["Hi Jon! I'm doing well, thanks. How about you?"],
  },
  {
    name: 'Jon Doe',
    sent: true,
    stamp: '12:38',
    text: ["I'm good too! Just wanted to check in. Are we still on for lunch tomorrow?"],
  },
  {
    name: 'Jane Smith',
    sent: false,
    stamp: '12:40',
    text: ["Yes, definitely! Let's meet at 1 PM at the usual spot."],
  },
  {
    name: 'Jon Doe',
    sent: true,
    stamp: '12:42',
    text: ['Sounds great. See you then!'],
  },
]

export default defineComponent({
  name: 'ChannelPage',

  data() {
    return {
      messages,
    }
  },

  methods: {
    async loadMore(index: number, done: (stop: boolean) => void) {
      done(true)
    },
  },
})
</script>
